import type { Config } from "tailwindcss";

// Design tokens extracted from design/stitch-export/*.html (task 2.1) - all
// four Stitch exports carry the identical token set (colors, radius,
// spacing, fontSize), confirmed by diff before extraction; only whitespace
// and a font-fallback addition differed between files.
const config: Config = {
  darkMode: "class",
  content: ["./app/**/*.{js,ts,jsx,tsx,mdx}", "./components/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#b9c7df",
        "on-tertiary-fixed": "#281901",
        "inverse-surface": "#303032",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#574325",
        primary: "#303e51",
        "on-surface-variant": "#44474c",
        tertiary: "#4d3a1c",
        "gap-mid": "#BAE6FD",
        "on-background": "#1b1b1d",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#665131",
        "bg-subtle": "#F8FAFC",
        "outline-variant": "#c4c6cd",
        "surface-bright": "#fbf9fa",
        "tertiary-fixed": "#fcdeb4",
        secondary: "#006591",
        "primary-fixed": "#d5e3fc",
        "inverse-on-surface": "#f2f0f2",
        "on-secondary-container": "#004666",
        "gap-high": "#FDE68A",
        "primary-container": "#475569",
        "surface-variant": "#e4e2e3",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#001e2f",
        "surface-container-high": "#eae7e9",
        "border-soft": "#F1F5F9",
        "inverse-primary": "#b9c7df",
        "surface-tint": "#515f74",
        "surface-container": "#efedef",
        "secondary-fixed": "#c9e6ff",
        "surface-dim": "#dbd9db",
        "surface-container-low": "#f5f3f5",
        "secondary-container": "#39b8fd",
        "on-primary-container": "#bbcae1",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#89ceff",
        "on-primary-fixed-variant": "#3a485b",
        error: "#ba1a1a",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        outline: "#75777d",
        surface: "#fbf9fa",
        "success-muted": "#14B8A6",
        "on-secondary-fixed-variant": "#004c6e",
        "on-surface": "#1b1b1d",
        "on-tertiary-container": "#e2c59d",
        "tertiary-fixed-dim": "#dfc29a",
        background: "#fbf9fa",
        "gap-low": "#E2E8F0",
        "surface-container-highest": "#e4e2e3",
        "on-primary-fixed": "#0d1c2e",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-gap": "16px",
        gutter: "24px",
        "margin-desktop": "40px",
        "container-max": "1120px",
        "margin-mobile": "16px",
        "card-padding": "24px",
      },
      fontFamily: {
        "headline-md": ["Public Sans", "sans-serif"],
        "headline-lg": ["Public Sans", "sans-serif"],
        "headline-sm": ["Public Sans", "sans-serif"],
        "body-md": ["Public Sans", "sans-serif"],
        "label-sm": ["Public Sans", "sans-serif"],
        "body-lg": ["Public Sans", "sans-serif"],
        "label-md": ["Public Sans", "sans-serif"],
        "headline-lg-mobile": ["Public Sans", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-sm": ["10px", { lineHeight: "12px", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg-mobile": ["26px", { lineHeight: "32px", fontWeight: "700" }],
      },
    },
  },
};

export default config;
